wiremock:
  server:
    files:
    stubs:
    - file:build/stubs/**/mappings/**/*.json
    port: 6565
stubrunner:
  stubsMode: REMOTE
  repositoryRoot: http://52.82.64.147:8081/nexus/content/repositories/snapshots
  ids:
  - capbility.thoughtworks.com:goods:+:12306